<?php
/**
 * Plugin Name:     KLarpen WP Cleanup
 * Plugin URI:      https://github.com/KLarpen/klarpen-wp-cleanup
 * Description:     Custom code to cleanup / remove / switch off unused WP features. The plugin intended to use by developers only: there is no UI! More details at the README.md and the plugin's file itself.
 * Author:          KLarpen
 * Author URI:      https://github.com/KLarpen
 * Text Domain:     klrpn-wpcleanup
 * Domain Path:     /languages
 * Version:         0.1.0
 *
 * @package         Klarpen_WP_Cleanup
 */

/**
 * Holder function for the command to deregister/dequeue unused core scripts and styles
 */
function klrpn_exclude_unused_scripts_n_styles(){
	if (!is_admin()) {
    # List of commands for the front-end only
		wp_deregister_script( 'wp-embed' );
	}
}
# Comment the action if not used
add_action( 'init', 'klrpn_exclude_unused_scripts_n_styles' );

# Completely switch off the Emoji: START
add_filter('emoji_svg_url', '__return_empty_string');
remove_action('wp_head', 'print_emoji_detection_script', 7);
remove_action('admin_print_scripts', 'print_emoji_detection_script');
remove_action('wp_print_styles', 'print_emoji_styles');
remove_action('admin_print_styles', 'print_emoji_styles');    
remove_filter('the_content_feed', 'wp_staticize_emoji');
remove_filter('comment_text_rss', 'wp_staticize_emoji');  
remove_filter('wp_mail', 'wp_staticize_emoji_for_email');
function wph_remove_emojis_tinymce($plugins) {
	if (is_array($plugins)) {
		return array_diff($plugins, array('wpemoji'));
	} else {
		return array();
	}
}
add_filter('tiny_mce_plugins', 'wph_remove_emojis_tinymce');
add_filter('option_use_smilies', '__return_false');
# Completely switch off the Emoji: END

# Remove standart widgets
add_action( 'widgets_init', 'klrpn_unregister_basic_widgets' );
function klrpn_unregister_basic_widgets() {
	unregister_widget('WP_Widget_Pages');
	unregister_widget('WP_Widget_Calendar');
	// unregister_widget('WP_Widget_Archives');
	// unregister_widget('WP_Widget_Links');
	// unregister_widget('WP_Widget_Meta');
	// unregister_widget('WP_Widget_Search');
	// unregister_widget('WP_Widget_Text');
	// unregister_widget('WP_Widget_Categories');
	// unregister_widget('WP_Widget_Recent_Posts');
	unregister_widget('WP_Widget_Recent_Comments');
	unregister_widget('WP_Widget_RSS');
	// unregister_widget('WP_Widget_Tag_Cloud');
	// unregister_widget('WP_Nav_Menu_Widget'); 
	// unregister_widget('WP_Widget_Media_Audio');
	// unregister_widget('WP_Widget_Media_Video');
	// unregister_widget('WP_Widget_Media_Gallery');
	// unregister_widget('WP_Widget_Media_Image');
}

# Удаление виджетов из Консоли WordPress
add_action( 'wp_dashboard_setup', 'klrpn_clear_wp_dash' );
function klrpn_clear_wp_dash(){
	$dash_side   = & $GLOBALS['wp_meta_boxes']['dashboard']['side']['core'];
	$dash_normal = & $GLOBALS['wp_meta_boxes']['dashboard']['normal']['core'];

	unset( $dash_side['dashboard_quick_press'] );       // Быстрая публикация
	unset( $dash_side['dashboard_primary'] );           // Блог WordPress
	unset( $dash_side['dashboard_secondary'] );         // Другие Новости WordPress

	// unset( $dash_normal['dashboard_incoming_links'] );  // Входящие ссылки
	// unset( $dash_normal['dashboard_recent_comments'] ); // Последние комментарии
	// unset( $dash_normal['dashboard_plugins'] );         // Последние Плагины
}
# Удаление виджета "Добро пожаловать"
remove_action( 'welcome_panel', 'wp_welcome_panel' );

# Switch off RSS Feeds
// remove_action( 'do_feed_rdf',  'do_feed_rdf',  10, 1 );
// remove_action( 'do_feed_rss',  'do_feed_rss',  10, 1 );
remove_action( 'do_feed_rss2', 'do_feed_rss2', 10, 1 );
remove_action( 'do_feed_atom', 'do_feed_atom', 10, 1 );

# Cleanup HTML Head generated by core: feed <link>, RSD etc. 
add_action( 'wp', function(){
	// remove_action( 'wp_head', 'feed_links_extra', 3 );
	// remove_action( 'wp_head', 'feed_links', 2 );
  remove_action( 'wp_head', 'rsd_link' );
  remove_action( 'wp_head', 'wlwmanifest_link' ); 
  remove_action( 'wp_head', 'wp_shortlink_wp_head', 10 );// Короткая ссылка - без ЧПУ <link rel='shortlink'

  # Resource hints to browsers for pre-fetching, pre-rendering and pre-connecting to web sites.
  # That's useful in most situations so keep next line commented unless you know what you are doing!
  // remove_action( 'wp_head', 'wp_resource_hints', 2); 
});

# Убираем версию WordPress
// add_filter('the_generator', '__return_empty_string');

/**
 * Отключаем принудительную проверку новых версий WP, плагинов и темы в админке,
 * чтобы она не тормозила, когда долго не заходил и зашел...
 * Все проверки будут происходить незаметно через крон или при заходе на страницу: "Консоль > Обновления".
 *
 * @see https://wp-kama.ru/filecode/wp-includes/update.php
 * @author Kama (https://wp-kama.ru)
 * @version 1.0
 */
if( is_admin() ){
	// отключим проверку обновлений при любом заходе в админку...
	remove_action( 'admin_init', '_maybe_update_core' );
	remove_action( 'admin_init', '_maybe_update_plugins' );
	remove_action( 'admin_init', '_maybe_update_themes' );

	// отключим проверку обновлений при заходе на специальную страницу в админке...
	remove_action( 'load-plugins.php', 'wp_update_plugins' );
	remove_action( 'load-themes.php', 'wp_update_themes' );

	// оставим принудительную проверку при заходе на страницу обновлений...
	//remove_action( 'load-update-core.php', 'wp_update_plugins' );
	//remove_action( 'load-update-core.php', 'wp_update_themes' );

	// внутренняя страница админки "Update/Install Plugin" или "Update/Install Theme" - оставим не мешает...
	//remove_action( 'load-update.php', 'wp_update_plugins' );
	//remove_action( 'load-update.php', 'wp_update_themes' );

	// событие крона не трогаем, через него будет проверяться наличие обновлений - тут все отлично!
	//remove_action( 'wp_version_check', 'wp_version_check' );
	//remove_action( 'wp_update_plugins', 'wp_update_plugins' );
	//remove_action( 'wp_update_themes', 'wp_update_themes' );

	/**
	 * отключим проверку необходимости обновить браузер в консоли - мы всегда юзаем топовые браузеры!
	 * эта проверка происходит раз в неделю...
	 * @see https://wp-kama.ru/function/wp_check_browser_version
	 */
	add_filter( 'pre_site_transient_browser_'. md5( $_SERVER['HTTP_USER_AGENT'] ), '__return_true' );
}

# Удаляем уведомление об обновлении WordPress для всех кроме админа
add_action( 'admin_head', function () {
	if ( ! current_user_can( 'manage_options' ) ) {
		remove_action( 'admin_notices', 'update_nag', 3 );
		remove_action( 'admin_notices', 'maintenance_nag', 10 );
	}
} );

/**
 * Remove unused section in the Theme Customizer.
 *
 * @param WP_Customize_Manager $wp_customize Theme Customizer object.
 */
function klrpn_customize_register( $wp_customize ) {
	// $wp_customize->remove_section( 'title_tagline' );
	$wp_customize->remove_section( 'colors' );
	// $wp_customize->remove_section( 'widgets' );
	// $wp_customize->remove_section( 'static_front_page' );
	// $wp_customize->remove_section( 'custom_css' );
}
# Uncomment if needed
// add_action( 'customize_register', 'klrpn_customize_register' );
